spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888

user:
  role: Applicant|Employer|Admin
  gender: Male|Female

jwt:
  secret: mnTxowKDJQhC7FsH7gTqLz7Rpi2YHfXO7nFJc8P8tQRGdeVd9rXvUgEGeZDUmbHokXmLcty+guTv1M5ZOE3RUw==
  expirationMs: 900000 # 15 minutes
