spring:
  application:
    name: user-profile-service
  config:
    import: optional:configserver:http://localhost:8888

jwt:
  secret: ======================Ll4Kcolnu=lL4dor7oh===========================