spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring:
        kafka:
          consumer:
            value:
              delegate: org.springframework.kafka.support.serializer.JsonDeserializer
    json:
      trusted-packages: "*"
    topic:
      notification: "notification-topic"
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: afdulrohmat03@gmail.com
    password: usvk qjbz ddhd qebx
    port: '587'