version: '3'

services:

  #  pgadmin:
  #    image: dpage/pgadmin4:latest
  #    container_name: pgadmin
  #    ports:
  #      - "5050:80"
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: admin@example.com
  #      PGADMIN_DEFAULT_PASSWORD: admin
  #    restart: unless-stopped
  #    networks:
  #      - microservices-network
  #
  #  auth-service-db:
  #    image: postgres:latest
  #    container_name: auth-service-db
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: root
  #      POSTGRES_DB: auth-service-db
  #    ports:
  #      - "54310:5432"
  #    restart: unless-stopped
  #    networks:
  #      - microservices-network
  #
  #  applicant-profile-service-db:
  #    image: postgres:latest
  #    container_name: applicant-profile-service-db
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: root
  #      POSTGRES_DB: applicant-profile-service-db
  #    ports:
  #      - "54320:5432"
  #    restart: unless-stopped
  #    networks:
  #      - microservices-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8085:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge