spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #        - id: catalog
        #          uri: http://localhost:8090
        #          predicates:
        #            - Path=/product/**, /category/**
        #          filters:
        #            - AuthFilter

        - id: job-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/jobs/**
          filters:
            - AuthFilter

        - id: auth-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    register-with-eureka: true

server:
  port: 8080