eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/

server:
  port: 8099

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: afdulrohmat03@gmail.com
    password: usvkqjbzddhdqebx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
